repos:
  # black repo for python formatting
  - repo: https://github.com/ambv/black
    rev: 22.12.0
    hooks:
      - id: black
  # Official repo for default hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.4.0"
    hooks:
      - id: check-xml
        exclude: "tools"
      - id: check-merge-conflict
      - id: mixed-line-ending
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: requirements-txt-fixer
